openapi: "3.0.0"
info:
  description: "Extreamly minimal node js server (Express, TypeScript, Jest, DB, Swagger)"
  version: "1.0.0" 
  title: "mini-node-ts"

servers: 
  - url: "http://localhost:8810"
tags:
  - name: "user"
    description: "Operations about user"

paths:
  /:
    x-swagger-router-controller: routes.config
    get:
      operationId: defaultRoute
      summary: "Check server's avilablity"
      responses:
        "200":
          description: "Response OK"

  /users/test:
    x-swagger-router-controller: routes.config
    get:
      operationId: testRequest
      summary: Test request for checking the user component, don't forget to change it or delete it
      responses:
        "200":
          description: "Request ran successfuly"

  # /users/login:
  #   post:
  #     tags:
  #       - "user"
  #     summary: "Logs user into the system"
  #     operationId: "loginUser"
  #     produces:
  #       - "application/json"
  #     parameters:
  #       - in: "body"
  #         name: "body"
  #         description: User's username and password
  #         required: true
  #         schema:
  #           $ref: "#/definitions/UserLoginObj"
  #     responses:
  #       "200":
  #         description: "successful operation"
  #         schema:
  #           $ref: "#/definitions/LoginResponseObj"
  #       "400":
  #         description: "Invalid username/password supplied"
  # /users/sign-up:
  #   post:
  #     tags:
  #       - "user"
  #     summary: "Signing up new user"
  #     operationId: "signup-user"
  #     produces:
  #       - "application/json"
  #     parameters:
  #       - in: "body"
  #         name: "body"
  #         description: New user data
  #         required: true
  #         schema:
  #           $ref: "#/definitions/User"
  #     responses:
  #       "200":
  #         description: "User created successfuly"
  #         schema:
  #           $ref: "#/definitions/ApiResponse"
  #       "500":
  #         description: "There is a problem with creating the user"
  # /users/return-something:
  #   get:
  #     tags:
  #       - "user"
  #     summary: "Do something"
  #     produces:
  #       - "application/json"
  #     responses:
  #       "200": 
  #         schema:
  #           $ref: "#definitions/ReturnObj"
        
# securityDefinitions:
#   petstore_auth:
#     type: "oauth2"
#     authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
#     flow: "implicit"
#     scopes:
#       write:pets: "modify pets in your account"
#       read:pets: "read your pets"
#   api_key:
#     type: "apiKey"
#     name: "api_key"
#     in: "header"